void print(char * buffer, int size);
void read(char * buffer);
void printRegisters();
void nlPrint();
void printErr();
void zoomIn();
void zoomOut();
int strCompare(char *s1, char*s2);
int strSize(char * word);
void history();
